apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-v2
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      version: v2.0.0
  template:
    metadata:
      labels:
        app: api
        version: v2.0.0
    spec:
      containers:
      - name: api-container
        image: localhost:32000/api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: v2.0.0
